### ISSUE TITLE
selecting text with mouse loses selection

### ISSUE THREAD

**Issue by ChuckIrvine** [bbatsov/prelude#1065]
When I select text with my mouse, about half the time, emacs loses my selection, causing typos. I've only started using Prelude recently. Have never had this problem prior to using Prelude. Any thoughts? Really like it though.

**Comment by AlainODea** [comment]
@ChuckIrvine are you new to Emacs or just new to Prelude? My comments below will hopefully not come across wrong. Just hoping to find where the problem is :)

On the new to Emacs side, Emacs does mouse selection pretty differently from other mainstream editors like Atom or VS Code. As soon as you click anywhere else (including other tabs, splits, or frames/windows) the mouse selection is lost. Getting familiar with Emacs key bindings and the killring will make it a much more productive experience (C-SPACE to start selection/mark, C-w to cut/kill, M-w to copy, C-y to paste, A-y to cycle through paste history/killring)

On the old hand Emacs, new to Prelude side, Prelude has a mouse-leave-editor-hook which autosaves and may be interfering with how you are used to using it.

**Comment by ChuckIrvine** [comment]
I’m a long time emacs user. I think the behavior I’m seeing is specific to prelude. I better understand how it is working now. In order to select a region with the mouse, I have to first left click where I want to start and then left click again and drag to select a region. If I just left click and drag immediately my region isn’t selected.

Another problem is that the emacs buffer is hyper sensitive to my mouse. I haven’t quite figured out exactly what’s happen, but I often have the current cursor location jump around unexpectedly.

**Comment by AlainODea** [comment]
In Emacs 25.1.1 on OS X I can reliably left click and drag to select without clicking first. I haven't tried this on Ubuntu or Windows. Has your mouse, mouse driver, or OS changed recently?

I find my cursor jumps in Prelude if I scroll with the trackpad or mouse. When I'm using a mouse I lock the scrollwheel to avoid this. When I was using Emacs on Windows and Ubuntu I also made sure to disable trackpad taps. They caused massive problems for me.

**Comment by ChuckIrvine** [comment]
I’m using emacs 24.5.1 on a mac. I’ll upgrade and see if that makes any difference. Thanks
