### ISSUE TITLE
[question] how could i change font size at start

### ISSUE THREAD

**Issue by poulpoulsen** [bbatsov/prelude#1110]
hello,
how could i change the font size at start? i use zenburn theme with emacs 25.1.2 on windows 81 64bit.

Regards
Poul

**Comment by KarlFish** [comment]
https://stackoverflow.com/questions/294664/how-to-set-the-font-size-in-emacs

Add the snippet in the linked question `(set-face-attribute 'default nil :height 200)` to `~/.emacs.d/personal/edits.el`. Create that file since it doesn't exist. 

Prelude is just a large configuration pre-assembled for you. With these small bug-fix type things, google is your friend. I found the linked question by searching `change emacs font size`

**Comment by poulpoulsen** [comment]
Hello,
i found a solution.
But sorry for a novice user, a simple google search presents a bunch of tips with only a small amount of positive solutions. Sometimes it works only with a pure emacs, some works with spacemacs, some tolds to put things in directories, which are not there and so on. Only a small amount of results works...
Special here: Why put in edits.el? I read about prelude, that every .el file inside personal is loaded and parsed. Someone else wrote, to put in configuration in emacs_config.el and so on.
puzzling
Regards
Poul

**Comment by KarlFish** [comment]
Ah. The name of the file doesn't really matter. All the `.el` files in personal are loaded.

I think just `.emacd.d/init.el` is loaded by default and in prelude the init specifies to load all the other files in the directory. 

In spacemacs all the little configurations like this go into the `~/.spacemacs` file, in the user config function
