### ISSUE TITLE
Warnings when starting with prelude

### ISSUE THREAD

**Issue by jbulow** [bbatsov/prelude#1117]
I see the following warnings when starting with prelude:
> Warning (bytecomp): Use ‘with-current-buffer’ rather than save-excursion+set-buffer
> Warning (bytecomp): ‘next-line’ is for interactive use only; use ‘forward-line’ instead.

I have these modules enabled:

`(require 'prelude-ido) ;; Super charges Emacs completion for C-x C-f and more
(require 'prelude-company)

(require 'prelude-c)
(require 'prelude-emacs-lisp)
(require 'prelude-js)
(require 'prelude-ocaml)
(require 'prelude-org) ;; Org-mode helps you keep TODO lists, notes and more
(require 'prelude-python)
(require 'prelude-scheme)
(require 'prelude-shell)
(require 'prelude-web) ;; Emacs mode for web templates
(require 'prelude-xml)
(require 'prelude-yaml)
`

**Comment by KarlFish** [comment]
These warnings are coming from `(require 'prelude-ocaml)` -->  `(require 'tuareg)` --> `(require 'caml`). The files in this package (`~/.emacs.d/elpa/caml-20151009.845/*.el`) have one call to `(next-line)` and lots of `save-excursion+set-buffer` calls. These files are downloaded from [this svn repository](https://caml.inria.fr/svn/ocaml/trunk/emacs/).

Maybe prelude should suggest following the instructions at [https://github.com/ocaml/tuareg#install](https://github.com/ocaml/tuareg#install) to for ocaml mode instead of the outdated melpa package?

small tip: Use triple back-ticks (\`\`\`) around your code

**Comment by bbatsov** [comment]
I think someone should probably update the MELPA recipe, but that's outside the scope of Prelude.
