### ISSUE TITLE
Prelude makes emacs slow

### ISSUE THREAD

**Issue by anriseth** [bbatsov/prelude#1131]
If I run emacs with prelude, there is a time lag between keystrokes and emacs responding. This disappears with `emacs -q`, so there seems to be something in prelude that is slowing things down on my system.

Prelude was working well until I ran `prelude-update` yesterday. This is the first time I've done an update in several months.

How can I go about debugging this? I have tried to run emacs with a clean/vanilla prelude from git master, and the problem persists.

Running emacs 25.3.1 on Ubuntu 16.04.

**Comment by anriseth** [comment]
UPDATE: It seems to me that the culprit is projectile. Commenting out lines related to projectile in `prelude-editor.el` fixes the problem.

**Comment by kirk86** [comment]
@anriseth I can verify that as well. Every time that I disable the projectile-mode everything goes back to normal. I don't notice any slow down. This was especially happening to me whenever I was accessing files with tramp.

**Comment by holocronweaver** [comment]
Occurs both on Mac and Ubuntu. Temporarily disabling projectile.

**Comment by Twey** [comment]
Happened to me on NixOS as well.  Updated Prelude, emacs becomes unusably slow.  Disabling Projectile fixes it.

**Comment by RadicalZephyr** [comment]
I've seen this happen, and through profiling saw that something within in projectile appeared to be the culprit.  However, that same time I also had the problem "vanish" in the same buffers without disabling projectile.  Seems like there's some edge case, probably in recursive directory searching that's not quite being handled correctly.

Does anyone have a 100% reliable way to reproduce this with a standard (no personalizations) Prelude distribution?

**Comment by mrzor** [comment]
Greetings! I'm chiming in to state that problem is alive and well inside my environment, and that the pain is slowly but surely increasing - it's been going on for 2 months+ :) 

I do not have a 100% reliable way to reproduce this with a standard Prelude distribution.

Most of the projects I work on live in my $HOME. Since the bug could be related to the file count or folder layout, I'm not sure how to get back to a standard non personalized Emacs Prelude without making a new user in a new $HOME. 

I blame a subprocess of (projectile?) for this - spamming CTRL-G usually results in one or more `Waiting for process to die...done` showing up in the Messages buffer. Turning projectile off with `M-x projectile-mode` does the trick.

Unfortunately, I couldn't find a way to opt-out of projectile at start up - it looks fairly weaved inside prelude's core.

**Comment by mrzor** [comment]
`C-c p f` : quite often dies or fails to perform entirely, spamming `Waiting for process to die...done` in `*Messages*`. I cannot prove it's related, but it _feels_ like the same lag, and as such, issue.

~~~~
C-c p f runs the command helm-projectile-find-file (found in
projectile-mode-map), which is an interactive compiled Lisp function
in ‘helm-projectile.el’.

It is bound to C-c p f, s-p f, <menu-bar> <tools> <Projectile> <Find
file>.
~~~~

I still have not figured out how I can pinpoint the source of this. A backtrace for process spawns or for `Wating for process to die...done` lines could maybe help me find out more. If someone has (modern|relevant) emacs debugging tricks to link to, that'd be very appreciated.

Futher observations : having more than one project "opened" - i.e. having buffers belonging to more than one project, seems to trigger the glitch more often - I can't prove it tho.

**Comment by bbatsov** [comment]
That was caused by an upstream bug in Projectile that was fixed since. See also the duplicate issue https://github.com/bbatsov/prelude/issues/1130
