### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by oystersauce8** [bbatsov/prelude#1135]
Can the README have some uninstall instructions?

**Comment by novakboskov** [comment]
Since Prelude is just an Emacs distribution it could be "uninstalled" the same way as any other Emacs configuration - simply delete `.emacs.d`. Everything related to init directory is stated in Emacs' [documentation](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html) itself.

If you think of uninstalling of particular package it is also done by a standard Emacs' method - `package.el` and it's documentation is at a standard location - The Emacs Manual [here](https://www.gnu.org/software/emacs/manual/html_node/emacs/Packages.html).

All in all, everything could be accomplished using uniform Emacs' methods and is covered in The Emacs Manual. Prelude is not an exception from any other Emacs configuration - distribution. That's why it shines IMHO. :)

**Comment by funston** [comment]
do you backup the .emacs.d first? seems like it just overwrote my .emacs.d

**Comment by bbatsov** [comment]
@funston The installer should have backed up your `.emacs.d` to an archive file. You can see the relevant code here https://github.com/bbatsov/prelude/blob/master/utils/installer.sh#L189

**Comment by funston** [comment]
that is to backup .emacs, not .emacs.d directory, right?

**Comment by bbatsov** [comment]
Nope, that's for `.emacs.d`. The code for backing up `.emacs` is above it.

**Comment by funston** [comment]
k, i see that now, but for some unknown reason it did not backup my .emacs.d when i installed.
