### ISSUE TITLE
turn off auto-fill

### ISSUE THREAD

**Issue by sshandilya** [bbatsov/prelude#116]
Any way to turn off the auto-fill mode in LaTeX mode?

I tried redefining prelude-latex-mode-defaults in my personal .el file:

```
(defun prelude-latex-mode-defaults ()
  (abbrev-mode +1))
```

But auto-fill mode is still on whenever I load a latex file...

**Comment by controesempio** [comment]
Right now the solution presented does not work (at least in my case): `add-hook` will add `(lambda () (auto-fill-mode -1))` at the beginning of  `prelude-latex-mode-hook`, so it will be executed before `prelude-latex-mode-defaults`. The net effect will be that `auto-fill-mode` is turned off and then on.

I've solved this by using the optional argument to `add-hook` which appends the instruction at the end of the list, instead of the beginning: `(add-hook 'prelude-latex-mode-hook (lambda () (auto-fill-mode -1)) t)`

By the way: I believe  `turn-off-auto-fill` and `(auto-fill-mode -1)` are exactly the same thing.

I was confused by the fact that the defaults are *at the end* of the list of hooks (so, they are run *last*), unless you append the new elements with the optional flag. Is there a reason why the defaults are packed into one single function, instead of being laid out "flat" in the list, so that one could remove some of them with `remove-hook`? What is the advantage?

[from the Emacs manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Setting-Hooks.html#Setting-Hooks)

> For a normal hook, hook functions should be designed so that the order in which they are executed does not matter. Any dependence on the order is asking for trouble.  However, the order is predictable: normally, function goes at the front of the hook list, so it is executed first (barring another add-hook call). If the optional argument append is non-nil, the new hook function goes at the end of the hook list and is executed last.

**Comment by lobisquit** [comment]
Hi everybody, I have tried every single solution proposed above but none of them actually works, since `auto-fill-mode` is still enabled every time the `tex` file is opened.
Any clue on a possible fix to this nasty behaviour?

**Comment by lobisquit** [comment]
Looking at this file, I have just noticed that the hook that `auto-fill` mode is triggered by this hook in [this file](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/latex/packages.el):
```lisp    
(when latex-enable-auto-fill
        (add-hook 'LaTeX-mode-hook 'latex/auto-fill-mode))
```
Setting the variable `latex-enable-auto-fill` to `nil` seems not to do the job, while disabling the hook turns out to be effective.
```lisp
(remove-hook 'LaTeX-mode-hook 'latex/auto-fill-mode)
```

**Comment by butala** [comment]
I have tried every suggested solution above to no avail. Can someone please suggest a solution?
