### ISSUE TITLE
suggestion: move (global-undo-tree-mode) elswhere so it will not interfere with installation of packages not supplied by prelude

### ISSUE THREAD

**Issue by bigos** [bbatsov/prelude#1173]
I have my own fork of prelude https://github.com/bigos/prelude and last night I decided to make it more up to date with the upstream version. When I started loading my configuration, I ran into lots of problems related to undo tree similar to that issue.

https://github.com/xiaohanyu/oh-my-emacs/issues/28

After a bit of searching it turns out that commenting out

`; (global-undo-tree-mode)`

in  prelude/core/prelude-editor.el solves the problem and compilation of the packages can continue? Is it possible that this is called too early and should be done at some later stage?

**Comment by bigos** [comment]
Seems like moving
`(global-undo-tree-mode)`
to the end of personal config file has worked for me, but is there a better place for it in Prelude?

**Comment by bigos** [comment]
is the end of `~/.emacs.d/init.el` a good place?

**Comment by bbatsov** [comment]
Hmm, I can't understand how the position of this can be causing such a problem. I've never encountered this and I don't recall anyone else reporting something similar.

**Comment by bigos** [comment]
Perhaps because I went too far with my fork and experimented with using org-mode to store personal configuration. I seem to have found a way around the problem. So you can take note of the problem and close the issue.

**Comment by mwasilew2** [comment]
I think I'm experiencing different symptoms of the same problem. As @bigos pointed out, it also looks to be the same as xiaohanyu/oh-my-emacs#28

Below are my findings in case someone else comes across this. I'm open to any suggestions, if you know a better solution, please let me know

I use my own emacs config which includes installation of evil (undo-tree is a dependency of evil) and there are a few things going wrong for me: installation of some modes fail (e.g. groovy), features of some modes fail (e.g. yasnippet dropdown menu)

they fail with the following error message:
```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  undo-tree-current(nil)
  (undo-tree-node-previous (undo-tree-current buffer-undo-tree))
  (and undo-tree-mode (not buffer-read-only) (not (eq t buffer-undo-list)) (undo-tree-node-previous (undo-tree-current buffer-undo-tree)))
```

disabling global-undo-tree-mode in evil with
`(global-undo-tree-mode 0)`
makes it go away, but evil is no longer capable of doing a redo

0.6.6 of undo-tree fixes the problem

How to get 0.6.6?

Undo-tree is not present in melpa at all, some even consider the project dead: https://www.reddit.com/r/emacs/comments/6fxcd3/advice_on_submitting_undotree_enhanced_to_melpa/

It is available in elpa, but the latest version in elpa is 0.6.5 (that's the version installed as a dependency of evil)

it seems to be available as a package in AUR and GNU Guix: https://repology.org/metapackage/emacs-undo-tree/versions

so if AUR and GNU Guix are not an option for you, how to get it from source?

link to the package website on emacswiki is outdated:
http://www.dr-qubit.org/Emacs_Undo_Tree_package.html (404)

here's an up to date link:
http://www.dr-qubit.org/undo-tree.html

and the git repo on that website with last commit in 2017 (the git server is pretty slow, sometimes unresponsive):
http://www.dr-qubit.org/git/undo-tree.git

there's a mirror of the dr-qubit's repo on github, but it's outdated:
https://github.com/akhayyat/emacs-undo-tree/blob/master/undo-tree.el

and here's a mirror I created on gitlab (it's up to date and responsive, I also wanted to make sure the repo is not lost):
https://gitlab.com/mwasilewski/undo-tree.git

checking out the repo and including it in emacs config did not make evil use it. undo-tree from elpa will get installed anyway because package manager will try to satisfy the dependency. Because of that you need to "tell your package manager that your local file is the undo-tree package"

I use use-package, so in my case it was:
```
git clone https://gitlab.com/mwasilewski/undo-tree
cp undo-tree/undo-tree.el ~/.emacs.d/site-lisp/undo-tree/undo-tree.el # site-lisp is my directory with custom lisp code
```

and in emacs config:
```
(use-package undo-tree
  :load-path "site-lisp/undo-tree/undo-tree"
  )
```
