### ISSUE TITLE
Backwards Compatibility with Emacs 24.5?

### ISSUE THREAD

**Issue by rachel-1** [bbatsov/prelude#1196]
On the description it says "Prelude is an enhanced Emacs 24.4+ distribution" but in the README it says "Prelude is compatible ONLY with GNU Emacs 25.1+." I'm running 24.5 and can't upgrade because I'm using a university-managed server. Are there any workarounds to get it working?

**Comment by bbatsov** [comment]
The problem is the following - while Prelude itself doesn't require Emacs 25, some of the packages it depends on have bumped their required Emacs version to 25. One option for you would be to just see which deps would refuse to install and pin them to older versions, as mentioned in the README, or simply remove them.
