### ISSUE TITLE
error: Package ‘undo-tree-’ is unavailable

### ISSUE THREAD

**Issue by samratroy** [bbatsov/prelude#1225]
Cannot complete setup in my Ubuntu 16.04 machine using Emacs 26.1. I get the error as given in the title.
"error: Package ‘undo-tree-’ is unavailable"

**Comment by samratroy** [comment]
Cannot complete setup in my Ubuntu 16.04 machine using Emacs 26.1. I get the error as given in the title.
"error: Package ‘undo-tree-’ is unavailable"

**Comment by adityaathalye** [comment]
As far as I can tell, this particular failure can happen due to unsigned packages, or incorrectly signed packages. I see that `undo-tree-0.6.5` available from the gnu package repo, is unsigned.

Workarounds are available.

See if this helps:
* review the advice at https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Installation.html
* try to identify the offending package (start emacs with --debug-init)
* add the package to the `package-unsigned-archives` list and restart emacs (ideally, after auditing the source code of your target package)
* you may need to do this at the top of prelude's init.el (set the list, before prelude tries to install packages)
* it's possible that more than one package is causing this problem

There's some advice out there to turn off signature checking entirely with `(setq package-check-signature nil)` --- see: https://stackoverflow.com/a/26110978 --- but I don't like this idea of very much (signatures exist for a good reason).

Please report back here with your findings. I'd be interested to learn if I'm wrong, and more interested to learn what worked for you. 

Also if this is a fundamental issue, prelude maintainers might be able to work out a proper fix.

**Comment by ceod** [comment]
Same report as OP, with similar config (ubuntu16.04 + emacs26.1 from the kellyk ppa.)

Additionally, I get a 

```failed to download 'gnu' archive```

message before emacs prelude terminates with

```error: Package ‘undo-tree-’ is unavailable```

Possibly related are: 

https://www.reddit.com/r/emacs/comments/apr9b2/bad_signature_from_gnu_elpa_signing_agent/

https://stackoverflow.com/questions/26108655/error-updating-emacs-packages-failed-to-download-gnu-archive

Haven't been able to resolve this yet.

Any news?

**Comment by aeweiwi** [comment]
Same here I get the same message


Warning (initialization): An error occurred while loading ‘c:/Users/username/.emacs.d/init.el’:

error: Package ‘undo-tree-’ is unavailable

**Comment by spaceotter** [comment]
I'm running into this too, with current master. I'm using windows and emacs is installed with msys2, which has version 26.1. If I try to package-list I get an additional error, which you can see in this pastebin I found (idk who posted this) https://pastebin.com/ttnqUcMm

`error in process sentinel: Error retrieving: https://elpa.gnu.org/packages/archive-contents "incomprehensible buffer" [2 times]`

However, the same "error in process sentinel" occurs with an empty .emacs.d - so it may not be an issue with prelude.

**Comment by spaceotter** [comment]
This looks like a consequence of this emacs bug: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34341
If you are seeing this issue, adding this temporary fix at the beginning of init.el may help:
`(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")`
Credit to npostavs in #emacs for helping me out.

**Comment by jcguu95** [comment]
@spaceotter 's result and @retiform 's reference solved the problem for me. I could not believe it happened almost half of year ago and hasn't been taken care of officially.. :(

**Comment by trago** [comment]
I have the same problem in emacs26

**Comment by trago** [comment]
> @spaceotter 's result and @retiform 's reference solved the problem for me. I could not believe it happened almost half of year ago and hasn't been taken care of officially.. :(

Solved for me doing that hack

**Comment by rafiks** [comment]
yup @spaceotter  workaround works.

**Comment by highkone** [comment]
For me installing newest emacs on debian sid fixed a problem. I also did the above mentioned addition to the init.el. That alone did not work for me on emacs versio I had. Also I have had problem lately with the certificate emacs uses to access the (m)elpa package sites, thus the reinstalling probably/possibly fixed the keyring issue too.

**Comment by bbatsov** [comment]
Installing Emacs 26.3 is the simplest way to solve this.

**Comment by wapcrazut** [comment]
> Installing Emacs 26.3 is the simplest way to solve this.

Recommended solution:

``` 
sudo add-apt-repository ppa:kelleyk/emacs
sudo apt update
sudo apt install emacs26
```

Then run `emacs26` on the terminal

**Comment by rafiks** [comment]
I can confirm that this works with emacs 26.3 on my Mac.
https://emacsformacosx.com/

**Comment by semperos** [comment]
Confirm Emacs 26.3 fixes this for me as well. Installed on Pop!_OS via the PPA [wapcrazut mentioned](https://github.com/bbatsov/prelude/issues/1225#issuecomment-538329298).

**Comment by samratroy** [comment]
Okay, revisiting this after quite sometime: two approaches solved the issue for me:
1. As has been so widely prescribed: updating emacs itself to the newest release.
2. Setting `package-check-signature` to `nil`.
Thanks.

**Comment by bootladder** [comment]
For Ubuntu 16.04, ppa:kelleyk/emacs does not have 26.3, so I built 26.3 from source and that solved the issue.

**Comment by bbatsov** [comment]
Btw, I wrote an entire article on the subject - https://metaredux.com/posts/2019/12/09/dealing-with-expired-elpa-gpg-keys.html

**Comment by serafss2** [comment]
Upgrading to 26.3 solved my problem.

I suggest just compiling emacs from source, the steps are fairly simple:

```
./configure
make
```

You then can just update the symlink in `/bin`:
```zsh
rm /bin/emacs
ln -s /opt/emacs-26.3/src/emacs /bin/emacs
```

I do these steps since 2014 and they didn't change since, this will remove your ppa dependence and always have the latest software, applies to any application - not like you need any other software than emacs eh

**Comment by 26-55-87-BuddhiLW** [comment]
Why not make it explicit in the homepage of the prelude repository? It's a common problem, over all.

**Comment by bbatsov** [comment]
Yeah, that's a good idea.

**Comment by smeierzubiesen** [comment]
> Btw, I wrote an entire article on the subject - https://metaredux.com/posts/2019/12/09/dealing-with-expired-elpa-gpg-keys.html

This is by far the most useful resource in all this chatter.
I would recommend, straight after cloning of prelude (et al.) to start emacs once, then after failed startup ```C-x-c``` to close, import the gpg key as per above, and bob's your auntie (or gender challenged uncle lol) the next start of emacs includes all tools that come with prelude redux etc...
