### ISSUE TITLE
Getting Clojure LSP mode to work

### ISSUE THREAD

**Issue by grav** [bbatsov/prelude#1291]
First I should say that I'm totally new to prelude, and have not used Emacs for quite a while. My general ambition is to try out Emacs and LSP to see if I can get some of the same experience that I had with IntelliJ and Cursive.

My question: what's the recommended way of getting clojure-lsp to work with Prelude?

I initially thought that, as long as clojure-lsp is installed and working, and uncommented `(require 'prelude-lsp)` in `~/.emacs.d/personal/prelude-modules.el`, it would work out of the box, ie starting up when loading a .clj file in a project.

When it didn't, I re-read the instructions for Emacs on clojure-lsp's homepage, but these refer to `use-package` which does not seem to work with prelude.

I also tried just running the `lsp-mode` command, but this did not seem to start the clojure-lsp server.

I then more or less randomly stumbled upon a message in the Clojurians slack that said to use `add-hook`. 

Reading a bit in the Prelude docs, I ended up adding the file in `~/.emacs.d/personal/clojure-lsp.el` with the following:

```
(require 'lsp-clojure)
(add-hook 'clojure-mode-hook #'lsp)
```

It works, but it doesn't seem to be documented anywhere, and I'm down to writing elisp, so I'm wondering if I'm on the right track?

**Comment by bbatsov** [comment]
> First I should say that I'm totally new to prelude, and have not used Emacs for quite a while. My general ambition is to try out Emacs and LSP to see if I can get some of the same experience that I had with IntelliJ and Cursive.

Generally Prelude leans on CIDER instead of `clojure-lsp`, but you can totallay use `clojure-lsp` as well. Just keep in mind that mixing the two might result is some weird interactions between them.

> When it didn't, I re-read the instructions for Emacs on clojure-lsp's homepage, but these refer to use-package which does not seem to work with prelude.

`use-package` is just a macro that expands into convential configuration code, there's nothing special about it. E.g. this:

```
(use-package lsp-mode
  :ensure t
  :hook ((clojure-mode . lsp)
         (clojurec-mode . lsp)
         (clojurescript-mode . lsp))
  :config
  ;; add paths to your local installation of project mgmt tools, like lein
  (setenv "PATH" (concat
                   "/usr/local/bin" path-separator
                   (getenv "PATH")))
  (dolist (m '(clojure-mode
               clojurec-mode
               clojurescript-mode
               clojurex-mode))
     (add-to-list 'lsp-language-id-configuration `(,m . "clojure")))
  (setq lsp-clojure-server-command '("bash" "-c" "clojure-lsp") ;; Optional: In case `clojure-lsp` is not in your PATH
        lsp-enable-indentation nil))```

Here everything in `config` can just go in your `clojure-lsp.el` file and you already figured out how to trigger the hooks normally (without `use-package`). Btw, the suggested configuration is a bit wrong as you don't need to mention any mode derived from `clojure-mode` explicitly. 

I'll extend the docs for this when I have some time.

**Comment by grav** [comment]
Great, thanks for your answer, Bozhidar!
