### ISSUE TITLE
Error in Process Sentinel when Emacs starts

### ISSUE THREAD

**Issue by zhfe99** [bbatsov/prelude#719]
I did a fresh install of the prelude package on my Mac with the Emacs version 24.3.1.
And then I put a `init.el` configuration file in the `~/.emacs.d/personal` folder. 
This `init.el` file contains only one line: 
`(desktop-save-mode 1)`

Whenever I start the Emacs, I got multiple following errors with the noisy beep sound:
   `error in process sentinel: Wrong type argument: stringp, nil [x times]`
where "x" equals to the number of directory (`dired-mode`) windows saved by the `desktop-save mode`.

So if I have 100 directories opened in the last time of using Emacs, I need wait forever to start Emacs because I will get 100 messages with the same error 
`error in process sentinel: Wrong type argument: stringp`

It is very annoying. I am wondering where there is a solution?

**Comment by stolowski** [comment]
I have been experiencing this for quite long time and I can cofirm the workaround with commenting out the above line in core/prelude-editor.el fixes it.

**Comment by bbatsov** [comment]
Guess @dgutov might have a look at this.

**Comment by dgutov** [comment]
Sorry, can't reproduce. I've tried several versions, and in 24.3 desktop behaved weirdly (not saving any windows aside from the current), but it did restore Dired window with `diff-hl-dired-mode` on fine.

No problems using a recent version from Emacs master or emacs-24.

Have you tried Emacs 24.4? IIRC the Desktop package received quite a few bugfixes before the last release. Also, if `emacs --debug-init` didn't help you before with this issue, it might start working in 24.4.

So, someone please give me a backtrace or a foolproof scenario I can follow on my machine. Preferably starting with `HOME=/tmp emacs`.

**Comment by stolowski** [comment]
I've been experiencing it both in emacs 24.3 and 24.4 but I have no idea how to reproduce it atm. I've started with a clean slate this morning (closed all buffers etc and restarted emacs) and the problem disappeared. Then I started working on source code tree of one of my work projects and at the end of the day the problem is back when I restart emacs. At that time I had a bunch of files opened in emacs, as well as a few directories in dired mode. I'll be keeping an eye on it to see if there is any pattern to reproduce.
