### ISSUE TITLE
Keymap clash with Ubuntu 14.10

### ISSUE THREAD

**Issue by thegeorgeous** [bbatsov/prelude#770]
Ubuntu's Unity uses Super based shortcuts on the desktop. This leads to clashes especially with Magit commands in Prelude. Any possible fixes for this?

**Comment by hbin** [comment]
I used to disable the \<super\> key by [Ubuntu Tweak](http://ubuntu-tweak.com/).

**Comment by holocronweaver** [comment]
Could you give some examples of specific clashes?

**Comment by anantpaatra** [comment]
Well, this was closed by the OP without an explanation but I experience such clashes as well. The super key is used by default in some Desktops and in tiling Window Managers (like `i3wm` and `Xmonad`) it is a fairly common key to be used as a modifier (instead of `Alt`), especially to Emacs users who relly on the `Meta` key a lot. Since tiling WM's are keyboard centered, they tend to make heavy usage of keybindings.

If `super` was a key with many applications in Emacs, adapting the WM's keybindings would perhaps _feel_ unquestionable, but since only a few keybindings use it in Prelude, I _feel_ the overall logic of using it in `Prelude` at all (by default) is faulty. Maybe I'm alone, of course, so just providing my experience.
