### ISSUE TITLE
Feature request: a better Clojure experience OOTB

### ISSUE THREAD

**Issue by yatesco** [bbatsov/prelude#962]
I imagine (no proof at all, just a hunch) the number of people who use emacs and Clojure might also use prelude?

Given that, it would be great if https://github.com/clojure-emacs/clj-refactor.el was integrated out of the box. I realise this also requires some middleware but given CIDER already shows warnings if middleware was missing I assume this isn't too hard?

If this was possible then could we upgrade the `prelude-cleanup-buffer-or-region` to:

``` clojure
(defun clean-clojure-file ()
  (interactive)
  (when (cider-connected-p)
    (cljr-clean-ns))
  (prelude-cleanup-buffer-or-region)
  (save-buffer))
(key-chord-define-global "cc" 'clean-clojure-file)
```

It could also run optionally as a hook when saving the buffer?

I also notice that whilst popups appear, their doc-string doesn't - could that be added as well?

It would also be great if https://github.com/magnars/multiple-cursors.el was integrated as well, as I find it invaluable for local renaming of Clojure symbols.

I realise that some of this could be filed against the respective projects however I haven't done that as this issue is specifically to enable that configuration out of the box.

I would submit a pull request but given that chunk of emacs lisp is my first ever home-grown you can probably see why it would be a bit out of my reach :-).

Thanks as ever for Prelude - makes the (at least my) world a better place.

**Comment by bbatsov** [comment]
My main issue is the problems caused by `nrepl-refactor` loading your code to generate a proper AST for it. If this functionality could be implemented in a safer manner it would have been in CIDER. I'd love to add the safer bits of of `clj-refactor` and `nrepl-refactor` to CIDER, but I don't want to push the problematic bits to users who generally have no idea why their code got evaluated mysteriously. 

I'm not involved in the development of `clj-refactor` and from time to time it gets out-of-sync with CIDER which is another concern of mine.

**Comment by yatesco** [comment]
Yes, I see. OK, shall I close this?

**Comment by ChipNowacek** [comment]
Any other suggestions for refactoring tools? Is `clj-refactor` unsafe to use generally?
