### ISSUE TITLE
Document setup under Windows

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/prelude#963]
I was reminded this would be useful when I saw http://stackoverflow.com/questions/35047859/how-to-install-emacs-prelude-on-windows

**Comment by hut8** [comment]
I just saw that answer. `~` expands to `C:\Users\<whatever>\AppData\Roaming` only when `$HOME`, or as they say in Windows, `%HOME%` is not set. Unfortunately it is not set by default. Setting `%HOME%` is the best option in my opinion. I can add this documentation since I've done it a few times, as long as you agree that that's a good method.

**Comment by blokeley** [comment]
I'm the author of that Stack Overflow question.
@hut8 please do add clear instructions to the documentation for us people on Windows.
The instructions for gnuTLS, find and grep might be helpful too.
